### ISSUE TITLE
Pakeisti "master" branch pasiekiamumą į protected.

### ISSUE THREAD

**Issue by atvarijonas** [amakauskaite/baltupiu-softas#12]
Checkboxes:
+Require pull request reviews before merging
+Require signed commits
+Include administrators

**Comment by amakauskaite** [comment]
![image](https://user-images.githubusercontent.com/24258297/37032975-f600bcfe-214c-11e8-987f-69ce992d1383.png)
Šitų užtenka, ane?

**Comment by atvarijonas** [comment]
Čia galima padiskutuot, bet iš mano pusės viskas ok

**Comment by atvarijonas** [comment]
-Require signed commits

Bereikalingas darbas bus pasiruošt šitam manau, galvojau built-in

**Comment by amakauskaite** [comment]
Kaip tik vakar prisėdau šito aiškintis ir, iš tiesų, vargo daugoka.

Panaikinau tą opciją, tai dabar jau leidžia merginti,
