### ISSUE TITLE
Duomenų bazės sukūrimas

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#19]

**Comment by amakauskaite** [comment]
@atvarijonas gal gali pakomentuoti, ką iš mano pusės reiktų padaryti, kad prisidėčiau prie DB kūrimo?

**Comment by amakauskaite** [comment]
Kiek supratau, tiek parašiau ir supushinau.
@atvarijonas  ir @maciukaite kai galėsit, pažiūrėkit :pray:
