### ISSUE TITLE
Paskyrai reikalingu langų implementavimas

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#25]

**Comment by amakauskaite** [comment]
Langai:
* Prisijungimo
* Paskyros sukūrimo
* Paskyros redagavimo

**Comment by amakauskaite** [comment]
[Prisijungimo ir registravimosi "langai"](https://jsfiddle.net/amakauskaite/ob3uzmwy/)
@maciukaite ir @CassiniUniverse  gal galit užmesti akį?

**Comment by maciukaite** [comment]
o mes ne xhtml naudosim? nes destytojas naudoja xhtml, siaip gerai + issokantys langai ir bus?

**Comment by amakauskaite** [comment]
xhtml kaip supratau, tai tik sintaksė biški skiriasi, ane? https://www.w3schools.com/html/html_xhtml.asp
Dėl langų, tai ten ne iššokantys, o tiesiog persidengiantys. Iš esmės galiu pakeist, bet dar nemačiau ar @CassiniUniverse įkėlė puslapio rėmus, kad galėčiau ant to viršaus daryti..

**Comment by CassiniUniverse** [comment]
Taip, aš dar nepadariau langų visų. Man labai patiko idėja, kad būtų
iššokantis langas. Gal tikrai jo reikia, o ne naujo puslapio kaip mano
makete.

2018 m. kovo 18 d. 17:49, Aušrinė <notifications@github.com> rašė:

**Comment by amakauskaite** [comment]
@maciukaite padariau pirminę login ir registration langų versiją -> galima naviguoti iš index.xhtml, kuriame įdėjau linkus. Ten kur adresai padariau, kad būtų html5 email tipo laukai, tai validuosis automatiškai, priklausomai nuo naršyklės. 
Taip pat bandžiau pridėti css, bet man kažkodėl nerado resursų, bandysiu taisyti sekmadienį prieš meetą arba kitą savaitę. 
Kaip suprantu, iš mano pusės liko paskyros redagavimo langas, css ir visko susiejimas su Birutės senu kodu?
Btw, viską laikau login-and-registration repository, ten susimerginau ir tavo kodo dalį

**Comment by amakauskaite** [comment]
Dabartiniai vartotojo redagavimo langų vaizdai:
![image](https://user-images.githubusercontent.com/24258297/40318872-d1cb08d0-5d2e-11e8-80c5-850c59709841.png)
![image](https://user-images.githubusercontent.com/24258297/40318887-ddb07040-5d2e-11e8-92b6-51895c8255c2.png)
![image](https://user-images.githubusercontent.com/24258297/40318923-f3d2d034-5d2e-11e8-8e94-ae4fdd652b9c.png)

**Comment by amakauskaite** [comment]
Langai implementuoti
