### ISSUE TITLE
Kodėl lentelės kaskart paleidus projektą sukuriamos naujos?

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#37]
Reiktų padaryti, kad create if not exist kiek aš suprantu, bet nežinau ar su hibernate galima taip.

**Comment by atvarijonas** [comment]
Specialiai nustatyta, pradžioj kol lenteles keitėm patogiau buvo. Su sekančiu pull request pakeisiu.

**Comment by maciukaite** [comment]
@atvarijonas kodel dabar isvis nekuria lenteliu? :dagger:
