### ISSUE TITLE
Kai vartotojas keičia slaptažodį, tada jis atsijungia

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#38]
Keičiant vartotojo slaptažodį neberodo, kad jis prisijungęs, kaip suprantu tai dėl to, nes lentelės eilutė pasikeitė. Gal žinai kaip sutvarkyt?

**Comment by atvarijonas** [comment]
Sumerginau branchą, peržiūrėsiu dabar

**Comment by maciukaite** [comment]
cia ne tas branch :) yra kitas branch user, kur yra ne tik login, bet ir info keitimas :)
p.s. ten dar sena login versija tai sumerginsiu tuoj
