### ISSUE TITLE
Užduočių specifikavimas

### ISSUE THREAD

**Issue by amakauskaite** [amakauskaite/baltupiu-softas#5]
Susmulkinti puslapyje [Darbo planas](https://github.com/amakauskaite/baltupiu-softas/wiki/Darbo-planas) esančias užduotis į smulkesnes

**Comment by Valiukonyte** [comment]
dokumentas google diske pavadinimu "užduotys(reikalavimai)". Administratoriaus užduotys/veikla nėra aiški.
