### ISSUE TITLE
Nuotraukos atvaizdavimas šalia prekės prekės lange

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#59]
Prekės lange turi matytis nuotrauką

**Comment by amakauskaite** [comment]
Šiuo metu matomas vaizdas:
![image](https://user-images.githubusercontent.com/24258297/40318545-a28e9b28-5d2d-11e8-8bb5-a8e12edddf20.png)
Tvarkingumo dėlei siūlau įdėti nuotrauką į rėmelį ir lentelę perkelti į dešinę prie jos, paliekant aprašymą apačioje

**Comment by CassiniUniverse** [comment]
![paveikslas](https://user-images.githubusercontent.com/22612905/40628952-cd761ac0-62d0-11e8-83bd-c694f2a37810.png)

**Comment by maciukaite** [comment]
@CassiniUniverse  man reiktu tarpo didesnio tarp foto ir info , ir tarpo tarp eiluciu. Isvis paglima pailti ta pacia lentele, tik ja i sona perkelt.
