### ISSUE TITLE
Kažkas išsikraipė :) (ką reikia taisyti)

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#66]
![image](https://user-images.githubusercontent.com/33057953/40226895-a33f0e6c-5a95-11e8-97d1-2e1ea20cc755.png)

Kai nedaug prekių yra man šitaip rodo, gal dėl to, kad naudoju Brave naršyklę :)

**Comment by amakauskaite** [comment]
Dalykai ištaisyti #68 , rekomenduoju peržiūrėti :)
