### ISSUE TITLE
Prieeiga prie github

### ISSUE THREAD

**Issue by atvarijonas** [amakauskaite/baltupiu-softas#7]
Trūksta prieeigos teisių šiems veiksmams:

- [ ] Issues kūrimui ir konfigūravimui

- [ ] Wiki puslapių kūrimui ir konfigūravimui

- [ ] Viskam

**Comment by amakauskaite** [comment]
Sveikas,

tau trūksta prieigos, nes nepatvirtinai, kad esi colaborator: 
![image](https://user-images.githubusercontent.com/24258297/36938179-afee2f1c-1f26-11e8-912c-02ac2ca38d7d.png)
Linkas: 
https://github.com/amakauskaite/baltupiu-softas/invitations
