### ISSUE TITLE
Vartotojo informacijos keitimas

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#77]
![image](https://user-images.githubusercontent.com/33057953/40575084-d71cfd50-60e6-11e8-93be-e3e92e87db32.png)
1. Pakeisti klaidos zinute
2. Padaryti, kad butu galima nuscrollinti iki mygtuku

**Comment by amakauskaite** [comment]
@maciukaite Pridėjau prie adreso keitimo lietuviškas žinutes. Dėl nuskrolinimo - tai arba reikia keisti footerį, kad jis būtų žemyn nuskrolinus (nes problema, kad jisai užeina ant duomenų), arba jį perkelti į kairę (kaip su index puslapiu), arba jį iš viso panaikinti, arba nieko nedaryti ir tiesiog išjungti žinutę. Galima pakelti ir formą tiesiog aukščiau ir žiūrėti, ar neužpildžius visų laukų žinutės taip žemai nenuslinks :smiley:

**Comment by amakauskaite** [comment]
@maciukaite pridėjau (ir tuoj supushinsiu) ir informacines žinutes, kai sėkmingai pakeisti duomenys:
![image](https://user-images.githubusercontent.com/24258297/40584942-f26e415a-61b2-11e8-987e-c1957a42d3d6.png)
Taip pat tikrinimą, ar senas slaptažodis nesutampa su nauju:
![image](https://user-images.githubusercontent.com/24258297/40584957-28281884-61b3-11e8-9d2c-21f99aa15003.png)
Lietuviški įspėjimai (be scrollinimo, deja):
![image](https://user-images.githubusercontent.com/24258297/40584970-624604f4-61b3-11e8-8594-c77016b9eb70.png)

**Comment by maciukaite** [comment]
nais. tada paliekam footeri kaip yra @amakauskaite
