### ISSUE TITLE
Administratoriaus prekiu sarasas

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#79]
![image](https://user-images.githubusercontent.com/33057953/40625163-73ad6c4e-62b9-11e8-969d-712e73ccea1a.png)
1. Reikia ne šalia, o iš karto į lauką dabartines reikšmes rašyt
![image](https://user-images.githubusercontent.com/33057953/40625202-9e17ac2e-62b9-11e8-83c3-21a1770b5412.png)
2. Jei lengva padaryt, tai kai nera foto, jos ir neleisk paspaust
3. Preke issitrina tik is 2tro karto
![image](https://user-images.githubusercontent.com/33057953/40625222-d3796ea2-62b9-11e8-97c9-b676493398d5.png)
4. Kategoriju pavadinimas turi buti
5. Nera klaidos pranesimo/sekmes pranesimo, kai preke pridedama
![image](https://user-images.githubusercontent.com/33057953/40625302-32b4e0e0-62ba-11e8-940b-c86dd124d2f3.png) 
6. Kai prideti preke ir nueini i prekiu langa, tai kaskart perkrovus yra ta preke pridedama + idejau nuoroda is google, neaisku, is kur deti nuoroda
7. Neprideda prekes jei ne visi laukai uzpildyti

**Comment by Valiukonyte** [comment]
dėl 7, nevisi laukai privalomi? ar tik kai kurie privalomi?
del 2, jeigu spaudei ant to krepselio su juodais konturais, jo background transparent, todėl nesimato

**Comment by maciukaite** [comment]
7. manau, aprasymas ir foto neturi buti privalimi (foto ir dabar pas mus ne visada yra)
2. transperent maciau, spaidziau ant to kito ir ne at obuoliaus

**Comment by amakauskaite** [comment]
Padariau visus laukus privalomus (kad nemestu kokiu nors klaidu).
Klaidu ir informacines zinutes taip pat pridetos, dar pridejau <br/> po foto

**Comment by amakauskaite** [comment]
@maciukaite @Valiukonyte ar dar reikes kokiu front end taisymu, susijusiu su admino prekemis ir ju sarasu?
