### ISSUE TITLE
Istorijos langų pataisymas

### ISSUE THREAD

**Issue by maciukaite** [amakauskaite/baltupiu-softas#87]
ištaisyti adminOrders. xmtl ir purchaseHistory.xhmtl

**Comment by amakauskaite** [comment]
Labas rytas :smiley_cat: 
![image](https://user-images.githubusercontent.com/24258297/40753011-cd757218-647a-11e8-81db-5224b1d31291.png)
![image](https://user-images.githubusercontent.com/24258297/40753032-de4e04f6-647a-11e8-9e06-de9fa2955bc2.png)
![image](https://user-images.githubusercontent.com/24258297/40754293-3ea3d898-6481-11e8-8363-8843a71bed3c.png)
![image](https://user-images.githubusercontent.com/24258297/40754646-fee228d4-6482-11e8-9649-494216406ca7.png)
